# Generated by Django 5.2.4 on 2025-08-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('usermail', models.CharField(max_length=250)),
                ('usersubject', models.CharField(max_length=500)),
                ('usermessage', models.TextField()),
            ],
        ),
    ]
