# Generated by Django 5.2.4 on 2025-10-31 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
